<?php

use Illuminate\Database\Seeder;

class DataRowsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('data_rows')->delete();
        
        \DB::table('data_rows')->insert(array (
            0 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'ID',
                'edit' => 0,
                'field' => 'id',
                'id' => 1,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'number',
            ),
            1 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => NULL,
                'display_name' => 'Name',
                'edit' => 1,
                'field' => 'name',
                'id' => 2,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            2 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => NULL,
                'display_name' => 'Email',
                'edit' => 1,
                'field' => 'email',
                'id' => 3,
                'order' => 3,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            3 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'Password',
                'edit' => 1,
                'field' => 'password',
                'id' => 4,
                'order' => 4,
                'read' => 0,
                'required' => 1,
                'type' => 'password',
            ),
            4 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'Remember Token',
                'edit' => 0,
                'field' => 'remember_token',
                'id' => 5,
                'order' => 5,
                'read' => 0,
                'required' => 0,
                'type' => 'text',
            ),
            5 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'Created At',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 6,
                'order' => 6,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            6 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 7,
                'order' => 7,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            7 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => NULL,
                'display_name' => 'Avatar',
                'edit' => 1,
                'field' => 'avatar',
                'id' => 8,
                'order' => 8,
                'read' => 1,
                'required' => 0,
                'type' => 'image',
            ),
            8 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsTo","column":"role_id","key":"id","label":"display_name","pivot_table":"roles","pivot":0}',
                'display_name' => 'Role',
                'edit' => 1,
                'field' => 'user_belongsto_role_relationship',
                'id' => 9,
                'order' => 10,
                'read' => 1,
                'required' => 0,
                'type' => 'relationship',
            ),
            9 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsToMany","column":"id","key":"id","label":"display_name","pivot_table":"user_roles","pivot":"1","taggable":"0"}',
                'display_name' => 'Roles',
                'edit' => 1,
                'field' => 'user_belongstomany_role_relationship',
                'id' => 10,
                'order' => 11,
                'read' => 1,
                'required' => 0,
                'type' => 'relationship',
            ),
            10 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'Settings',
                'edit' => 0,
                'field' => 'settings',
                'id' => 11,
                'order' => 12,
                'read' => 0,
                'required' => 0,
                'type' => 'hidden',
            ),
            11 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 2,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'ID',
                'edit' => 0,
                'field' => 'id',
                'id' => 12,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'number',
            ),
            12 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 2,
                'delete' => 1,
                'details' => NULL,
                'display_name' => 'Name',
                'edit' => 1,
                'field' => 'name',
                'id' => 13,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            13 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 2,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'Created At',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 14,
                'order' => 3,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            14 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 2,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 15,
                'order' => 4,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            15 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'ID',
                'edit' => 0,
                'field' => 'id',
                'id' => 16,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'number',
            ),
            16 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 3,
                'delete' => 1,
                'details' => NULL,
                'display_name' => 'Name',
                'edit' => 1,
                'field' => 'name',
                'id' => 17,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            17 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'Created At',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 18,
                'order' => 3,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            18 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 19,
                'order' => 4,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            19 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 3,
                'delete' => 1,
                'details' => NULL,
                'display_name' => 'Display Name',
                'edit' => 1,
                'field' => 'display_name',
                'id' => 20,
                'order' => 5,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            20 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => NULL,
                'display_name' => 'Role',
                'edit' => 1,
                'field' => 'role_id',
                'id' => 21,
                'order' => 9,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            21 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 8,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => 0,
                'field' => 'id',
                'id' => 68,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'text',
            ),
            22 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 8,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Title',
                'edit' => 1,
                'field' => 'title',
                'id' => 69,
                'order' => 2,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            23 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 8,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Logo',
                'edit' => 1,
                'field' => 'logo',
                'id' => 70,
                'order' => 3,
                'read' => 1,
                'required' => 0,
                'type' => 'image',
            ),
            24 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 8,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Created At',
                'edit' => 1,
                'field' => 'created_at',
                'id' => 71,
                'order' => 4,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            25 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 8,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 72,
                'order' => 5,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            26 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 9,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => 0,
                'field' => 'id',
                'id' => 74,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'text',
            ),
            27 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 9,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Title',
                'edit' => 1,
                'field' => 'title',
                'id' => 75,
                'order' => 2,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            28 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 9,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Logo',
                'edit' => 1,
                'field' => 'logo',
                'id' => 76,
                'order' => 3,
                'read' => 1,
                'required' => 0,
                'type' => 'image',
            ),
            29 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 9,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Created At',
                'edit' => 1,
                'field' => 'created_at',
                'id' => 77,
                'order' => 4,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            30 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 9,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 78,
                'order' => 5,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            31 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 10,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => 0,
                'field' => 'id',
                'id' => 80,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'text',
            ),
            32 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 10,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Installation Date',
                'edit' => 1,
                'field' => 'installation_date',
                'id' => 81,
                'order' => 2,
                'read' => 1,
                'required' => 0,
                'type' => 'date',
            ),
            33 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 10,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Title of society',
                'edit' => 1,
                'field' => 's_title',
                'id' => 82,
                'order' => 3,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            34 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 10,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Description',
                'edit' => 1,
                'field' => 'description',
                'id' => 83,
                'order' => 4,
                'read' => 1,
                'required' => 0,
                'type' => 'text_area',
            ),
            35 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 10,
                'delete' => 1,
                'details' => '{}',
            'display_name' => 'Video Link (Vimeo)',
                'edit' => 1,
                'field' => 'video',
                'id' => 84,
                'order' => 5,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            36 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 10,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Created At',
                'edit' => 1,
                'field' => 'created_at',
                'id' => 85,
                'order' => 6,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            37 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 10,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 86,
                'order' => 7,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            38 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 10,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Images',
                'edit' => 1,
                'field' => 'images',
                'id' => 87,
                'order' => 10,
                'read' => 1,
                'required' => 0,
                'type' => 'multiple_images',
            ),
            39 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 10,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Client Name',
                'edit' => 1,
                'field' => 'client_name',
                'id' => 88,
                'order' => 8,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            40 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 10,
                'delete' => 1,
                'details' => '{"model":"\\\\App\\\\Country","table":"countries","type":"belongsTo","column":"country_id","key":"id","label":"title","pivot_table":"countries","pivot":"0","taggable":"0"}',
                'display_name' => 'country',
                'edit' => 1,
                'field' => 'realisation_belongsto_country_relationship',
                'id' => 89,
                'order' => 12,
                'read' => 1,
                'required' => 0,
                'type' => 'relationship',
            ),
            41 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 10,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Logo',
                'edit' => 1,
                'field' => 'logo',
                'id' => 90,
                'order' => 9,
                'read' => 1,
                'required' => 0,
                'type' => 'image',
            ),
            42 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 10,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'City',
                'edit' => 1,
                'field' => 'city',
                'id' => 91,
                'order' => 11,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            43 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 10,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Country Id',
                'edit' => 1,
                'field' => 'country_id',
                'id' => 92,
                'order' => 12,
                'read' => 1,
                'required' => 0,
                'type' => 'hidden',
            ),
            44 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 11,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => 0,
                'field' => 'id',
                'id' => 93,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'text',
            ),
            45 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 11,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'First Name',
                'edit' => 1,
                'field' => 'first_name',
                'id' => 94,
                'order' => 2,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            46 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 11,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Last Name',
                'edit' => 1,
                'field' => 'last_name',
                'id' => 95,
                'order' => 3,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            47 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 11,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Location',
                'edit' => 1,
                'field' => 'location',
                'id' => 96,
                'order' => 4,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            48 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 11,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Phone',
                'edit' => 1,
                'field' => 'phone',
                'id' => 97,
                'order' => 5,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            49 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 11,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Email',
                'edit' => 1,
                'field' => 'email',
                'id' => 98,
                'order' => 6,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            50 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 11,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Created At',
                'edit' => 1,
                'field' => 'created_at',
                'id' => 99,
                'order' => 7,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            51 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 11,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 100,
                'order' => 8,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            52 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 12,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => 0,
                'field' => 'id',
                'id' => 101,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'text',
            ),
            53 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 12,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Mesure',
                'edit' => 1,
                'field' => 'mesure',
                'id' => 102,
                'order' => 2,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            54 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 12,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Largeur',
                'edit' => 1,
                'field' => 'largeur',
                'id' => 103,
                'order' => 3,
                'read' => 1,
                'required' => 0,
                'type' => 'number',
            ),
            55 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 12,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Espace',
                'edit' => 1,
                'field' => 'espace',
                'id' => 104,
                'order' => 4,
                'read' => 1,
                'required' => 0,
                'type' => 'number',
            ),
            56 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 12,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Hauteur',
                'edit' => 1,
                'field' => 'hauteur',
                'id' => 105,
                'order' => 5,
                'read' => 1,
                'required' => 0,
                'type' => 'number',
            ),
            57 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 12,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'P Palier Base',
                'edit' => 1,
                'field' => 'p_palier_base',
                'id' => 106,
                'order' => 6,
                'read' => 1,
                'required' => 0,
                'type' => 'image',
            ),
            58 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 12,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'P Palier Haut',
                'edit' => 1,
                'field' => 'p_palier_haut',
                'id' => 107,
                'order' => 7,
                'read' => 1,
                'required' => 0,
                'type' => 'image',
            ),
            59 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 12,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'P Ensembre',
                'edit' => 1,
                'field' => 'p_ensembre',
                'id' => 108,
                'order' => 8,
                'read' => 1,
                'required' => 0,
                'type' => 'image',
            ),
            60 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 12,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Societe',
                'edit' => 1,
                'field' => 'societe',
                'id' => 109,
                'order' => 9,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            61 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 12,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Name',
                'edit' => 1,
                'field' => 'name',
                'id' => 110,
                'order' => 10,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            62 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 12,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Phone',
                'edit' => 1,
                'field' => 'phone',
                'id' => 111,
                'order' => 11,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            63 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 12,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Email',
                'edit' => 1,
                'field' => 'email',
                'id' => 112,
                'order' => 12,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            64 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 12,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Address',
                'edit' => 1,
                'field' => 'address',
                'id' => 113,
                'order' => 13,
                'read' => 1,
                'required' => 0,
                'type' => 'text_area',
            ),
            65 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 12,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Codepostal',
                'edit' => 1,
                'field' => 'codepostal',
                'id' => 114,
                'order' => 14,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            66 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 12,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'City',
                'edit' => 1,
                'field' => 'city',
                'id' => 115,
                'order' => 15,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            67 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 12,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Country',
                'edit' => 1,
                'field' => 'country',
                'id' => 116,
                'order' => 16,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            68 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 12,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Description',
                'edit' => 1,
                'field' => 'description',
                'id' => 117,
                'order' => 17,
                'read' => 1,
                'required' => 0,
                'type' => 'text_area',
            ),
            69 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 12,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Created At',
                'edit' => 1,
                'field' => 'created_at',
                'id' => 118,
                'order' => 18,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            70 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 12,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 119,
                'order' => 19,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            71 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 12,
                'delete' => 1,
                'details' => '{"model":"\\\\App\\\\Models\\\\User","table":"users","type":"belongsTo","column":"user_id","key":"id","label":"email","pivot_table":"contacts","pivot":"0","taggable":"0"}',
                'display_name' => 'users',
                'edit' => 1,
                'field' => 'devi_belongsto_user_relationship',
                'id' => 120,
                'order' => 20,
                'read' => 1,
                'required' => 0,
                'type' => 'relationship',
            ),
            72 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 12,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'User Id',
                'edit' => 1,
                'field' => 'user_id',
                'id' => 121,
                'order' => 20,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            73 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 12,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Devis Path',
                'edit' => 1,
                'field' => 'devis_path',
                'id' => 122,
                'order' => 21,
                'read' => 1,
                'required' => 0,
                'type' => 'file',
            ),
        ));
        
        
    }
}